sudo: required

language: node_js
node_js:
  - "stable"

services:
  - docker

before_install:
  - docker build -t akachi/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true akachi/docker-react npm run test -- --coverage
#   deploy: #This deploys the whole folder onto elasticbeanstalk so
#   #it's the production Dockerfile that would be used by
#   #elasticbeanstalk to startup this app
#     provider: elasticbeanstalk
#     region: "us-east-2" #region you selected when creating the elb application
#     app: "docker-react" #the aws elb app name
#     env: "DockerReact-env" #the aws elb app environment
#     bucket_name: "elasticbeanstalk-us-east-2-709165253790" #s3 storage location for all apps deployed to this region
#     bucket_path: "docker-react" #name of the folder where this app you're targeting is located or going to exist
#     on:
#       branch: master #Only deploy when master branch is updated
#     access_key_id: $AWS_ACCESS_KEY #Environment variable generated
#                                    #in IAM of AWS but stored in travis ci
#     secret_access_key:
#       secure: "$AWS_SECRET_KEY" # Another environment variable
#       #generated in IAM of AWS but stored in travis ci
